# Generated by Django 2.0.5 on 2018-06-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyTask',
            fields=[
                ('csrf_token', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=60)),
                ('file_name', models.CharField(max_length=60)),
            ],
        ),
    ]
